"""empty message

Revision ID: 01535903a3ee
Revises: 40d7da1a9068
Create Date: 2024-09-15 17:23:08.034780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01535903a3ee'
down_revision = '40d7da1a9068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
